# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test CI with Gradle & SpringBoot project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Copying the boot jar file to docker location
      run: cp -f build/libs/springboot-ci-demo-0.0.1-SNAPSHOT.jar /var/lib/docker/tmp/docker-builder141767639/
      
    - name: Preparing docker image
      run: docker build -t build/libs/spring-boot-test-project:spring-boot-test-project_v1.0 ./docker-related
      
